### ISSUE TITLE
Create a coverage checklist for String#trimStart and trimEnd

### ISSUE THREAD

**Issue by leobalter** [bocoup/test262#122]
## trimStart

- esid: sec-string.prototype.trimstart
- [ ] function length
- [ ] function name
- [ ] prop-desc (property descriptor)
- trimString
  -  RequireObjectCoercible
    - [ ] TypeError if `this` is undefined
    - [ ] TypeError if `this` is null

## trimEnd

- esid: sec-string.prototype.trimend
- [ ] length
- [ ] name
- [ ] prop-desc

**Comment by spectranaut** [comment]
First try for checklist:

## trimStart
- esid: sec-string.prototype.trimstart
- [ ] *length.js* function length
- [ ] *name.js* function name
- [ ] *prop-desc.js* property descriptor
- TrimString
  - RequireObjectCoercible
    - [ ] *this-value-not-obj-coercible.js* TypeError if `this` is undefined
    - [ ] *this-value-not-obj-coercible.js* TypeError if `this` is null
  - ToString
    - [ ] *this-value-boolean-true.js* Return "true" if `this` is type Boolean true
    - [ ] *this-value-boolean-false.js* Return "false" if `this` is type Boolean false
    - [ ] *this-value-symbol.js* TypeError if `this` is Symbol
    - ToPrimitive
      - [ ] Abrupt complete if get attribute Symbol.toPrimitive abrupt completes
      - [ ] Abrupt complete if Symbol.toPrimitive abrupt completes
      - [ ] "Symbol.toPrimitive" is always called before "toString" and "valueOf"
      - [ ] TypeError if Symbol.toPrimitive returns a object
      - OrdinaryToPrimitive
        - [ ] "toString" is always called before "valueOf" 
        - [ ] "valueOf" used in case of nothing else
        - [ ] TypeError if "Symbol.toPrimitive", "toString", and "valueOf" not defined
        - [ ] TypeError if "toString" returns object
        - [ ] TypeError if "valueOf" returns object
        - [ ] Abrupt complete if toString abrupt completes
        - [ ] Abrupt complete if valueOf abrupt completes
        - [ ] Abrupt complete if get attribute toString abrupt completes
        - [ ] Abrupt complete if get attribute valueOf abrupt completes 
    - [ ] if "symbol.toPrimitive" or "toString" or "valueOf" return number, returns string 
    - [ ] if "symbol.toPrimitive" or "toString" or "valueOf" return boolean, returns string
    - [ ] if "symbol.toPrimitive" or "toString" or "valueOf" return Symbol, TypeError
    - [ ] if "symbol.toPrimitive" or "toString" or "valueOf" return string, return string
    - [ ] if "symbol.toPrimitive" or "toString" or "valueOf" return undefined, return "undefined"
    - [ ] if "symbol.toPrimitive" or "toString" or "valueOf" return null, return "null"
    - NumberToString
      - [ ] *this-value-number-nan.js* Given NaN, return "NaN"
      - [ ] *this-value-number-infinity.js* Given Infinity, return "Infinity"
      - [ ] *this-value-number-negative0.js* Given -0, return "-0"
      - [ ] *this-value-number-1.js* Given 1, return "1"
- [ ] Given a string with any whitespace and line terminantors at index 0, return a string without them

## trimEnd

- esid: sec-string.prototype.trimend
- [ ] *length.js* function length
- [ ] *name.js* function name
- [ ] *prop-desc.js* property descriptor
- TrimString
  - RequireObjectCoercible
    - [ ] *this-value-not-obj-coercible.js* TypeError if `this` is undefined
    - [ ] *this-value-not-obj-coercible.js* TypeError if `this` is null
  - ToString
    - [ ] *this-value-boolean-true.js* Return "true" if `this` is type Boolean true
    - [ ] *this-value-boolean-false.js* Return "false" if `this` is type Boolean false
    - [ ] *this-value-symbol.js* TypeError if `this` is Symbol
    - ToPrimitive
      - [ ] Abrupt complete if get attribute Symbol.toPrimitive abrupt completes
      - [ ] Abrupt complete if Symbol.toPrimitive abrupt completes
      - [ ] "Symbol.toPrimitive" is always called before "toString" and "valueOf"
      - [ ] TypeError if Symbol.toPrimitive returns a object
      - OrdinaryToPrimitive
        - [ ] "toString" is always called before "valueOf" 
        - [ ] "valueOf" used in case of nothing else
        - [ ] TypeError if "Symbol.toPrimitive", "toString", and "valueOf" not defined
        - [ ] TypeError if "toString" returns object
        - [ ] TypeError if "valueOf" returns object
        - [ ] Abrupt complete if toString abrupt completes
        - [ ] Abrupt complete if valueOf abrupt completes
        - [ ] Abrupt complete if get attribute toString abrupt completes
        - [ ] Abrupt complete if get attribute valueOf abrupt completes 
    - [ ] if "symbol.toPrimitive" or "toString" or "valueOf" return number, returns string 
    - [ ] if "symbol.toPrimitive" or "toString" or "valueOf" return boolean, returns string
    - [ ] if "symbol.toPrimitive" or "toString" or "valueOf" return Symbol, TypeError
    - [ ] if "symbol.toPrimitive" or "toString" or "valueOf" return string, return string
    - [ ] if "symbol.toPrimitive" or "toString" or "valueOf" return undefined, return "undefined"
    - [ ] if "symbol.toPrimitive" or "toString" or "valueOf" return null, return "null"
    - NumberToString
      - [ ] *this-value-number-nan.js* Given NaN, return "NaN"
      - [ ] *this-value-number-infinity.js* Given Infinity, return "Infinity"
      - [ ] *this-value-number-negative0.js* Given -0, return "-0"
      - [ ] *this-value-number-1.js* Given 1, return "1"
- [ ] Given a string with any whitespace and line terminantors at the last indexed location, return a string without them

**Comment by leobalter** [comment]
This is an excellent checklist.

**Comment by leobalter** [comment]
You can also add a check list for trimLeft and trimRight. They should be considerably small, as on call behavior is not necessary to test after you assert they are just references for trimStart and trimEnd.

**Comment by spectranaut** [comment]
## trimRight
- esid: #sec-string.prototype.trimright
- [ ] *length.js* function length
- [ ] *name.js* function name
- [ ] *prop-desc.js* property descriptor
- [ ] reference to trimRight the same as reference to trimEnd

## trimLeft
- esid: sec-string.prototype.trimleft
- [ ] *length.js* function length
- [ ] *name.js* function name
- [ ] *prop-desc.js* property descriptor
- [ ] reference to trimLeft the same as reference to trimStart

**Comment by spectranaut** [comment]
Made an issue on tc39/test262 repo:
https://github.com/tc39/test262/issues/1237

Moving this to done in the project!
