### ISSUE TITLE
Improve coverage for Typed Arrays

### ISSUE THREAD

**Issue by brianloveswords** [bocoup/test262#47]
- Int8Array
- Uint8Array
- Uint8ClampedArray
- Int16Array
- Uint16Array
- Int32Array
- Uint32Array
- Float32Array
- Float64Array

**Comment by brianloveswords** [comment]
There's a helper function that iterates over the constructors, but it's only used in one place right now – want to confirm that we can use it in a whole bunch of places.

**Comment by leobalter** [comment]
#457 is already covering some parts for Typed Arrays and the intrinsic %TypedArray% object.

I'm trying to identify a general list to test TypedArrays to complete coverage from there:
- [ ] 22.2.1.1 %TypedArray% ( ) - all steps
- [ ] 22.2.1.2 %TypedArray% ( length ) - all steps
- [ ] 22.2.1.3 %TypedArray% ( typedArray ) - all steps
- [ ] 22.2.1.4 %TypedArray% ( object ) - all steps
- [ ] 22.2.2.1 %TypedArray%.from ( source [ , mapfn [ , thisArg ] ] ) - all steps
- [ ] 22.2.2.2 %TypedArray%.of ( ...items ) - all steps
- [ ] 22.2.2.4 get %TypedArray% [ @@species ]
- [ ] All steps on 22.2.3 items
- [ ] 22.2.4.1 steps 3 and 4 - return abrupt from getPrototypeOf on the constructor. This is hard to achieve, but it sounds possible using Proxies
- [ ] 22.2.4.1 step 5 - "If IsConstructor (super) is false, throw a TypeError exception." - I still need to figure out how to reach that part

Extra and curious:
- [ ] 22.1.5.2.1 %ArrayIteratorPrototype%.next( ) step 8

---

I believe this task should be split on many other subtasks, it's way larger than I thought as it is. We can use a lot of knowledge from similar API on Array methods (specially on the prototype methods) but this is still a lot of work here.

**Comment by leobalter** [comment]
Other extras:

Array.isArray (TypedArray instances are not Array Exotic Objects)
Array.from
Array.of
Array.prototype methods used on TypedArray objects
